spring:
  datasource:
    url: ${DB_URL}
    username: changeit
    password: changeit
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update